# Base image : TODO

# copy the opencv deb package to the image.
# TODO

# install the opencv package with and dependencies
# TODO

# copy the GAE app.
# TODO

# adapt options to be able to bind with jni part of opencv.
ENV CLASSPATH #TODO
ENV _JAVA_OPTIONS -Djava.library.path= #TODO
